# Generated by Django 3.2.6 on 2021-08-27 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAppProject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.TextField(default=None, max_length=30),
        ),
    ]
