# Generated by Django 3.2.6 on 2021-08-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAppProject', '0002_auto_20210827_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Upload',
        ),
    ]
